apiVersion: batch/v1
kind: Job
metadata:
  name: job-1
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["echo", "hello"]
      restartPolicy: Never
  backoffLimit: 2

